import { ProductEntity } from "../../../entities/product.entity";
import { ProductModel } from "../models/product.model.pg";

export class ProductMapper {
  toEntity({
    id,
    type,
    name,
    msrp,
    rarity,
    imageUrl,
    releaseDate,
    cardMarketLink,
    cardkingdomBuyListLink,
    abugamesBuyListLink,
    fullSetLink,
    tcgpLink,
    bricklinkLink,
    psaLink,
    number,
    boosterCount,
    productSetId,
    tags,
    keyword,
    note,
    blocked,
    createdAt,
    updatedAt,
  }: ProductModel): ProductEntity {
    return {
      id,
      type,
      name,
      msrp,
      rarity,
      imageUrl,
      releaseDate,
      cardMarketLink,
      cardkingdomBuyListLink,
      abugamesBuyListLink,
      fullSetLink,
      tcgpLink,
      bricklinkLink,
      psaLink,
      number,
      boosterCount,
      productSetId,
      note,
      tags,
      keyword,
      blocked,
      createdAt,
      updatedAt,
    };
  }
}
